name: Manual Export Trigger

on:
  workflow_dispatch:

jobs:
  call-export:
    uses: common-voice/sentence-collector/.github/workflows/export.yaml@main
    secrets:
      COMMON_VOICE_BRANCH: ${{ secrets.COMMON_VOICE_BRANCH }}
      COMMON_VOICE_ORG: ${{ secrets.COMMON_VOICE_ORG }}
      COMMON_VOICE_REPO: ${{ secrets.COMMON_VOICE_REPO }}
      GH_KEY: ${{ secrets.GH_KEY }}
      GH_USERNAME: ${{ secrets.GH_USERNAME }}
      SC_EXPORT_BASE_URL: ${{ secrets.SC_EXPORT_BASE_URL }}
